
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve('#{script}', {paths: [process.argv[1]]})",
    __dir__
  ]).strip
end




# Require RN’s pods script and RN Permissions’ setup script
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!


target 'MyApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'                
  pod 'Google-Maps-iOS-Utils'     
 
  setup_permissions([
    'LocationWhenInUse',
    # 'LocationAlways',   # uncomment only if you truly need background location
    'FaceID',
  ])

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-maps/Google', :path => rn_maps_path



pre_install do |installer|
  $RNMapboxMaps.pre_install(installer)
end

  post_install do |installer|
   $RNMapboxMaps.post_install(installer)
    react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)
  end
end

